### ISSUE TITLE
Configure selection window width/size

### ISSUE THREAD

**Issue by erikw** [rgroli/other.nvim#17]
Broken out from https://github.com/rgroli/other.nvim/pull/16#issuecomment-1282247670

--

Would it be possible to add configuration to make the selection window larger, so that one can see a bit more of the path?

![Screen Shot 2022-10-18 at 13 32 34](https://user-images.githubusercontent.com/175286/196419889-0a622cab-6dbf-42b1-a595-91e4a346b96d.png)

**Comment by rgroli** [comment]
Hi, 

now the filename take up all available space. And there is a new config-option to set the window size as a number between 0 and 1.

Cheers!

**Comment by erikw** [comment]
@rgroli great thanks, it works!
