### ISSUE TITLE
Splits not working when there are multiple other files

### ISSUE THREAD

**Issue by erikw** [rgroli/other.nvim#19]
I just noticed that when there are multiple other files and one selects with the pop-up menu, then the horizontal or vertical splits are not used but the selected other file opens in the current window. See video recording:

https://user-images.githubusercontent.com/175286/198975454-3ed92e49-ab88-4614-8c6d-8f32f0cf2876.mov

In this video I select "a" in the menu for both tries of the split commands.

**Comment by rgroli** [comment]
Hi, 

I see that you are confused when using `:OtherSplit` and a filepicker shows up that the default action does not open the file in a split. That was actually always the case, as I intended to use the `OtherSplit` and `OtherVSplit` for perfect matches. 
What you could always do was: 

- To open the selected line without split press `<cr>` or `o`
- To open the selected line in a split press `v`
- To open the selected line in a vertical split press `s`

But as it seems, I forgot to document that 😠 (Which I will do now)

After our last pr I also introduced the shortcuts and additional keymaps. 

- To open a file by its shortcut without split press `<shortcutkey>`
- To open a file by its shortcut in a split press `<shift-shortcutkey>` (so basically uppercase shortcutkey)
- To open a file by its shortcut in a vertical-split press `<c-shortcutkey>`

Does this help you with the issue or do you think it makes sense to change the default-behaviour in the filepicker (pressing `<cr>` or `o` or `<shortcutkey>`) depending on how the filepicker was called initially (`:Other`, `:OtherSplit` or `:Othervsplit`).

**Comment by rgroli** [comment]
Hi, 
you can now configure the default keybinding :)
