### ISSUE TITLE
per-project mappings?

### ISSUE THREAD

**Issue by will** [rgroli/other.nvim#20]
The mappings seem like they could be represented in json. Do you think it'd be a good idea to look for something like `.mappings.json` in the project root as a place to do custom mappings?

**Comment by mandos** [comment]
You can use **exrc** and manually modify mapping options
```lua
-- file: .nvim.lua in project folder
local mappings = require("other-nvim").getOptions().mappings
table.insert(mappings, {
	pattern = "/src/app/(.*)/.*.html$",
	target = "/src/app/%1/%1.component.ts",
	context = "view",
})
```
I haven't checked it with details but on first glance it's working.

**Comment by rgroli** [comment]
@mandos Wow! That's really great - I didn't even know **exrc** existed. Will add this to the readme. 
Thanks!

**Comment by mandos** [comment]
@rgroli It was an obsolete feature in Neovim, but they implemented a safe version of it.

My advice, maybe you could consider extending the API with some function to add additional mapping.

PS. BTW nice plugin.

**Comment by qlibp** [comment]
Not sure how to integrate it with something like neoconf plugin, which use json file for configuration, instead of using lua/vimscript.

I think using yaml/json is the correct way to configure per-project settings.
