### ISSUE TITLE
Option to create other file

### ISSUE THREAD

**Issue by weeman1337** [rgroli/other.nvim#22]
Use case: I am editing a source code file and I want to create the test file that doesn't exist yet.

It would be handy if other.nvim would support creating the other file.

**Comment by rgroli** [comment]
The plugin detects non existing files now. They have a special marker in the filepicker window. 
When you pick the file, the file will be created. 

This behaviour is now the default. When you want the old behaviour back just set the config option `showMissingFiles` to false.
