### ISSUE TITLE
File path

### ISSUE THREAD

**Issue by timtyrrell** [rgroli/other.nvim#23]
I was looking to shift over to this plug from projectionist but nothing something weird related to path.  When I trigger `:Other` I see the full path on my machine:

<img width="805" alt="Screen Shot 2022-11-24 at 5 53 04 PM" src="https://user-images.githubusercontent.com/100535/203880663-6b104f97-b484-4402-a580-9fb094848ff8.png">

And when opened, it shows the full path as seen in my airline plugin, as well:

<img width="603" alt="Screen Shot 2022-11-24 at 6 01 11 PM" src="https://user-images.githubusercontent.com/100535/203880678-bd3f838c-b095-4df8-826e-0de6933dfb24.png">

Where normally it only shows the local path scoped to the repo I am working on, for example:

<img width="169" alt="Screen Shot 2022-11-24 at 6 00 56 PM" src="https://user-images.githubusercontent.com/100535/203880751-a4ce5436-d881-4551-b40e-da43c012c130.png">

Is there any more info I can provide to debug this? I don't know that this is an issue, but annoying/distracting, thanks!

**Comment by rgroli** [comment]
@timtyrrell The filepicker shows the path relative to the cwd now. I can't say anything about airline though. 

I have been using lualine for ages and there is an option to display any path absolute or relative to the cwd. Maybe there is something similar in airline..

**Comment by timtyrrell** [comment]
I switched to lualine a while back 👍
