### ISSUE TITLE
Mapping the current directory

### ISSUE THREAD

**Issue by MichaelAquilina** [rgroli/other.nvim#30]
Hello! Apologies if this is documented somewhere, but I tried following the examples and did have much like trying to map the following for python -> python test files.

If we have a file with the following path:

my/code/files/foo.py

Then it should map to:

**tests**/my/code/files/**test**_foo.py

This is a fairly standard pattern in python projects.

However I am struggling getting other.nvim to match the "current" project directory generically.

I've tried the following:

```lua
require("other-nvim").setup({
    -- [...]
    mappings = {
        -- custom mapping
        {
            pattern = "/(.*)/(.*).py$",
            target = "/test/%1/test_%2.py",
            context = "tests"
        }
    },
    -- [...]
})
```

But I quickly realised this would map the example I gave you to `/tests/absolute/path/to/project/my/code/files/test_foo.py`

Is there a way to get `other.nvim` to specify the "current directory" as part of the pattern and target configuration?

**Comment by rgroli** [comment]
Looking at your example again I think when you are removing the leading slashes in the pattern and target the issue could be solved. 
Also: Try showMissingFiles in the config to false. This will keep the plugin from trying to create non-existing files. 

Cheers!

**Comment by kuzyo** [comment]
@MichaelAquilina Here is my way to mapping to `tests` directory.
```
        {
          context = "[TESTS]",
          pattern = '(.*)/(.*).tsx$',
          target = '%1/__tests__/%2.test.tsx',
        },
```
