### ISSUE TITLE
Suggesting repeated other spec files

### ISSUE THREAD

**Issue by gugahoi** [rgroli/other.nvim#31]
Not sure if I am doing something wrong with my mappings however it seems that "Other" is suggesting a forever repeating pattern of `*.spec.ts` to `*.spec.spec.ts`, etc... I've looked at the builtin golang mapping and tried to replicate it for my typescript project.

## config

```lua
return {
  "rgroli/other.nvim",
  keys = {
    { "<leader>ll", "<cmd>:Other<CR>",       desc = "Other: File" },
    { "<leader>lp", "<cmd>:OtherSplit<CR>",  desc = "Other: Split" },
    { "<leader>lv", "<cmd>:OtherVSplit<CR>", desc = "Other: V Split" },
    { "<leader>lc", "<cmd>:OtherClear<CR>",  desc = "Other: Clear" },
  },
  config = function()
    require("other-nvim").setup({
      mappings = {
        {
          pattern = "(.*).spec.ts$",
          target = "%1.ts",
          context = "implementation",
        },
        {
          pattern = "(.*).ts$",
          target = "%1.spec.ts",
          context = "test",
        },
      },
    })
  end,
}
```

When using `:Other` in a `spec.ts` file, it suggests the following:

![image](https://github.com/rgroli/other.nvim/assets/355877/1d3a5248-ca40-4c82-b2f0-e15ce5f76cca)

Obviously `spec.spec.ts` is incorrect so how would I configure it to make sure this doesn't happen?

Could the mappings be "auto reversible" where if a pattern matches a target, then the target should also match the pattern?

Thanks in advance!

**Comment by rgroli** [comment]
Hey there,

To avoid this using regex, you'd need a negative lookahead, but unfortunately, the Lua regex engine doesn't support that. However, I believe the main problem lies in the plugin setting called `showMissingFiles`, which is set to true by default. So, whenever a pattern matches but the file is not there yet, a suggestion pops up. Simply setting it to false should do the trick and make everything work smoothly.

Cheers
