### ISSUE TITLE
Suggestion: Support for Angular Services

### ISSUE THREAD

**Issue by greggannicott** [rgroli/other.nvim#33]
Great plugin! I really appreciate you've taken the time to write it.

Something I'd find very useful is if for Angular it also supported Services.

Essentially when inside of a `*.service.ts` file, you'd have the option of `:Other test` which takes you to the spec file.

And when inside of a `*.service.spec.ts` file, you'd have the option of `:Other service` (rather than `component`).

Thanks again!

**Comment by rgroli** [comment]
Hi, thanks for your suggestion. I just added the mapping to the default angular mapping. 
Cheers :)
