### ISSUE TITLE
[SUGGESTION] c{,pp} header and source files

### ISSUE THREAD

**Issue by dtomvan** [rgroli/other.nvim#36]
In a c or project, often times you will find c or cpp files bearing the same name and path as a neighbor h or hpp file, respectively. I saw that there are builtin mappings, so I figured it would be nice to have one of those for c and cpp.

**Comment by rgroli** [comment]
@dtomvan Great idea, I encourage you to make an pr. That should be really easy to do. Just add a file in the builtin/mappings directory. 

It's not that I can't do it, but rather that I am not familiar with details of programming in c.
