### ISSUE TITLE
Question: What's the syntax used in target field?

### ISSUE THREAD

**Issue by qlibp** [rgroli/other.nvim#39]
I try to match all lua file wihtin workspace(just for experiment), but I got no match at all, which is weird. Can I use regex in target field?

```
{
   pattern = "(.*).py",
   target = ".*lua$"
}
```

**Comment by rgroli** [comment]
@qlibp In the target you can use glob patterns and reference the groups from the pattern.

So just removing the the $ from the target should work already.
