### ISSUE TITLE
Use custom highlight groups

### ISSUE THREAD

**Issue by b0o** [rgroli/other.nvim#40]
Currently, highlights are [hard-coded](https://github.com/rgroli/other.nvim/blob/cba4e5feb0c0a703acc9b78bc64422ac1469c468/lua/other-nvim/helper/window.lua#L166-L187) to built-in highlight groups. This means users can't customize the appearance of the Other.nvim specifically, it might look quite bad:

![2023-11-28_19-08-34_region](https://github.com/rgroli/other.nvim/assets/21299126/871ff773-9fb4-4cfa-8686-8917932f80d9)

It would be better if there were Other.nvim-specific highlight groups so that users could override them.

**Comment by rgroli** [comment]
@b0o Great suggestion, I implemented two custom hightlightgroups. `OtherSelector` and `OtherUnderlined`
