### ISSUE TITLE
Keep default openCommand when invoking `OtherSplit` et al. and selecting in picker

### ISSUE THREAD

**Issue by b0o** [rgroli/other.nvim#42]
If I run `OtherSplit` and the picker shows up, it would be nice to be able to press `<Cr>` and open in a vsplit rather than in the current window. This doesn't seem possible currently, so I need to consciously remember to hit `s` to open in a split, which I usually forget to do. 

Perhaps a new `open_file_default` action could be added which would use whatever openCommand Other was invoked with:

```
  keybindings = {
    ['<Cr>'] = 'open_file_default()',
    o = 'open_file()',
    t = 'open_file_tabnew()',
    v = 'open_file_vs()',
    s = 'open_file_sp()',
  },
```

**Comment by rgroli** [comment]
@b0o Also great find. It should just work now. Thank you!

**Comment by b0o** [comment]
Awesome, thanks for fixing all of these!
