### ISSUE TITLE
Expose local findOther function as API

### ISSUE THREAD

**Issue by m-deg** [rgroli/other.nvim#44]
I would like to build a function where i can ripgrep within both current file and list of other files. But this is not possible because findOther method is local. If you expose this method, this plugin will be more usable.

**Comment by rgroli** [comment]
@m-deg Thanks for the suggestion! 

I created a hook for this functionality. Look in the README for `onFindOtherFiles` this gives you a lua table with all the matches everytime the `findOther` method is run. 

Another option is to rely on the global variable `vim.g.other_lastmatches` which always hold the table with the last matches.

**Comment by m-deg** [comment]
Thanks, but i want this API to work even if findOther is not called. Essentially, when i go to a .cpp file, i want to find .h file programmatically on Lua instead of waiting until user triggers findOther call. i also don't want to trigger the whole thing programmatically because i don't want to necessarily navigate to the other file.

**Comment by rgroli** [comment]
@m-deg Alright, I see. I just made it public 😄

**Comment by m-deg** [comment]
![image](https://github.com/rgroli/other.nvim/assets/81925072/00bf90e7-ed8e-4bdb-8f19-72e810896694)

Thanks! You are awesome :)
