### ISSUE TITLE
Is it possible to go "back" to the "main" file?

### ISSUE THREAD

**Issue by farzadmf** [rgroli/other.nvim#49]
Hi there, the plugin is very useful to navigate to the Python test file (in my use case).

I have created the following mapping for my Python files:
```lua
{
  pattern = '(.*)/src/(.*)/(.*).py',
  target = '%1/test/%2/test_%3.py',
  context = 'test',
}
```

I was wondering if there's a way to go "back" to my main file (basically to alternate between them).

I know I can use [Neo]vim's built-in `C-^` mapping for this, but it could really be useful if I can use this plugin to do that.

**Comment by rgroli** [comment]
@farzadmf Yes, that would be done be adding a second pattern to go back. 
So in your case that would ___roughly___ be..

```lua
{
  pattern = '(.*)/test/(.*)/test_(.*).py',
  target = '%1/src/%2//%3.py',
  context = 'src',
}
```

Note: that's not tested but I think you get the idea.. You can also have a look at the built-in-mappings. There is also a lot of mapping back.

**Comment by rgroli** [comment]
@farzadmf Yes it's the default lua.. Best documentation about it as far as i know is here https://www.lua.org/manual/5.1/manual.html and there you should look at chapter "5.4.1 – Patterns"

**Comment by farzadmf** [comment]
Thank you very much @rgroli , I appreciate it
