### ISSUE TITLE
Thanks for inspiring. 🙏

### ISSUE THREAD

**Issue by sshelll** [rgroli/other.nvim#52]
I just built an similar plug [telescope-switch.nvim](https://github.com/sshelll/telescope-switch.nvim) based on telescope.

Thanks for your inspiration. 🙏

**Comment by rgroli** [comment]
Nice! Congratulations on the launch! 
Telescope integration is also on the roadmap for other.nvim 😄 So I will definetly have a look at your plugin and maybe get inspired back 😊 Cheers!
