### ISSUE TITLE
not works fine on sveltekit

### ISSUE THREAD

**Issue by ryoppippi** [rgroli/other.nvim#53]
Hi!
I found that the latest version of other.nvim does not work for my configuration.

I found that this happens after 6913629 commit.

How to reproduce
- check my config https://github.com/ryoppippi/dotfiles/blob/96bdffc0f8cc61fc10bc3a376cbf527ac243b36b/nvim/lua/plugin/other.lua#L1
- create example directory like this
```sh
ex
├── +page.server.ts
├── +page.svelte
└── +page.ts
```

- Open `+page.ts` then run `Other` command
  - at d36a66a
    - <img width="500" alt="Screenshot 2024-05-05 at 08 15 10" src="https://github.com/rgroli/other.nvim/assets/1560508/20d485c3-5ea2-4c3e-86bc-e0117e5a3fb7">
  - at 6913629
    - no file listed
    - <img width="538" alt="Screenshot 2024-05-05 at 08 21 04" src="https://github.com/rgroli/other.nvim/assets/1560508/e72e7dec-b2bc-4a6b-a4c3-2663cc601885">

- Also open `+page.svelte` then run `Other` command 
  - at d36a66a 
    - <img width="329" alt="Screenshot 2024-05-05 at 08 16 04" src="https://github.com/rgroli/other.nvim/assets/1560508/85a6d902-ea4e-4d69-b828-069b152a4eff">

  - at 6913629
    - weird file created.....
    - <img width="322" alt="Screenshot 2024-05-05 at 08 19 44" src="https://github.com/rgroli/other.nvim/assets/1560508/15cb904d-4e00-4c92-a802-86ec1d2a7ccd">

**Comment by rgroli** [comment]
@ryoppippi This issue should now be fixed.. But I also saw a problem with your config. 

You have 
```lua
local sveltekit_target = {
	{ target = "/%1/%+%2.svelte", context = "view" },
	{ target = "/%1/%+%2\\(*.ts\\|*.js\\)", context = "script", transform = "remove_server" },
	{ target = "/%1/%+%2\\(*.ts\\|*.js\\)", context = "script", transform = "add_server" },
}
```
where you use the keyword `transform` where it should be `transformer`

**Comment by ryoppippi** [comment]
@rgroli 
Oh really!
Thanks I'll modifiy it.
If I have estra issues, I'll create it.

Thank you so much
