### ISSUE TITLE
Result matches are cached?

### ISSUE THREAD

**Issue by alexgorbatchev** [rgroli/other.nvim#55]
I found that when having multiple targets matched, after opening one target, all subsequent calls for `.open()` will open the same target w/o giving me a choice.

```
          {
            pattern = "src/.*/([^.]+).(tsx?)$",
            target = {
              {
                target = "**/%1.test.%2",
                context = "test",
              },
              {
                target = "**/%1.stories.%2",
                context = "stories",
              },
            },
          },
```

**Comment by rgroli** [comment]
Hi,

there is the option "rememberBuffers" which does that. It defaults to true. Setting it to false should resolve your issue,

Cheers!
