### ISSUE TITLE
Allow pattern functions

### ISSUE THREAD

**Issue by weeman1337** [rgroli/other.nvim#58]
For advanced use-cases it would be great if `pattern` could also be a function, that returns the matches.

Then I could write code analysing the string or use advanced patterns with [LPeg](https://www.inf.puc-rio.br/~roberto/lpeg/) for example.

If this is something you could consider for other.nvim, I am open to provide a PR @rgroli

**Comment by rgroli** [comment]
That's a really great idea!
Very open to a pr.. :-) I didn't know LPeg, but that seems way more powerful than the default regex implementation.  

Thanx for contributing!
