### ISSUE TITLE
Idea for improvement: allow multiple targets for one mapping

### ISSUE THREAD

**Issue by be-ndee** [rgroli/other.nvim#8]
It would be cool to have the possibility to define multiple targets for one pattern and also with different transformers:

```
{
    pattern = "(.*).ts$",
    targets = {
        "%1.spec.ts",
        {
            target = "%1.html",
            transformer = "camelToKebap"
        }
    }
}
```

**Comment by rgroli** [comment]
I implemented that. I did it almost excatly as suggested here. Check the README for details. Also the internal default angular mappings already use this way of implementation.
